def smile_mouth():
    pendown()
    pensize(6)
    forward(4)
    left(3)
happy = input("happy or not?")
if happy == "happy":
    penup()
    setposition(0,-100)
    pendown()
    begin_fill()
    color("yellow")
    circle(100)
    end_fill()
    penup()
    setposition(-25,50)
    pendown()
    begin_fill()
    color("black")
    circle(10)
    end_fill()
    penup()
    setposition(25,50)
    pendown()
    begin_fill()
    color("black")
    circle(10)
    end_fill()
    penup()
    setposition(-75,0)
    right(90)
    
    for i in range(60):
        smile_mouth()
